= Library template

FIXME: my new template.

== Usage

FIXME: write usage documentation!

This is a template project for use with https://github.com/seancorfield/deps-new[deps-new].
As originally generated, it will produce a new library project when run:

----
$ clojure -Sdeps '{:deps {org.rssys/libtemplate {:git/sha "1229c9dc7030c2f53ac5461ec54c7d37b2cd9fbf" :git/url "https://github.com/redstarssystems/libtemplate.git"}}}' -Tnew create :template org.rssys/libtemplate :name myusername/mycoollib
----
or clone this project and run from its folder:
----
$ clojure -Sdeps '{:deps {org.rssys/libtemplate {:local/root "."}}}' -Tnew create :template org.rssys/libtemplate :name myusername/mycoollib :target-dir ../mycoollib
----





Assuming you have installed `deps-new` as your `new` "tool" via:

[source,bash]
----
clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.4.9"}' :as new
----

____

Note: once the template has been published (to a public git repo), the invocation will be the same, except the `:local/root` dependency will be replaced by a git or Maven-like coordinate.

____

Run this template project's tests (by default, this just validates your template's `template.edn`
file – that it is valid EDN and it satisfies the `deps-new` Spec for template files):

----
$ clojure -T:build test
----

== License

Copyright © 2021 Mike Ananev

_EPLv1.0 is just the default for projects generated by `clj-new`: you are not_
_required to open source this project, nor are you required to use EPLv1.0!_
_Feel free to remove or change the `LICENSE` file and remove or update this_
_section of the `README.md` file!_

Distributed under the Eclipse Public License version 1.0.
