== Library template
:Author:            Mike Ananev
:Date:              29/01/2022
:git:               https://git-scm.com[git]
:clojure-deps-cli:  https://clojure.org/guides/getting_started[clojure deps cli]
:tools-build:       https://clojure.org/guides/tools_build[tools-build]
:deps-new:          https://github.com/seancorfield/deps-new[deps-new]
:build-clj:         https://github.com/seancorfield/build-clj[build-clj]
:babashka:          https://github.com/babashka/babashka[babashka]
:toc:

=== Intro

This `Library template` helps you to quick start new library project using {clojure-deps-cli} and {deps-new}.

This `Library template` provides:

- project control using {babashka} tasks;
- building Clojure project using {tools-build};
- editor configuration via `.editorconfig` file;
- configured `clj-kondo` linter;
- configured `cljstyle` formatter;
- run tests using https://github.com/lambdaisland/kaocha[kaocha].

This template will give you the following basic project workflow:
[source, bash]
----
mike@mbp02 ✗ bb tasks
The following tasks are available:

clean        Clean target folder
build        Build deployable jar file for this project
install      Install deployable jar locally (requires the pom.xml file)
deploy       Deploy this library to Clojars
test         Run tests
repl         Run Clojure repl
outdated     Check for outdated dependencies
format       Format source code
lint         Lint source code
requirements Install project requirements
----

See also:

* https://github.com/redstarssystems/apptemplate[Application template]

== Usage

Before run this template ensure you have installed {deps-new} and {babashka} (see <<_install_prerequisites>>). +

To generate new library project run:

[source, bash]
----
$ clojure -Sdeps '{:deps {org.rssys/libtemplate {:git/sha "a9e39846672390f08853435a3f0226ee7a52cb6f" :git/url "https://github.com/redstarssystems/libtemplate.git"}}}' -Tnew create :template org.rssys/libtemplate :name com.example/lib01

cd lib01
----
or clone this project and run from its folder:

[source, bash]
----
$ clojure -Sdeps '{:deps {org.rssys/libtemplate {:local/root "."}}}' -Tnew create :template org.rssys/libtemplate :name com.example/lib01 :target-dir ../lib01

cd ../lib01
----

NOTE: Please, see `README.adoc` in a root folder of created project.


=== Install prerequisites

All these tools you need to install only once.

. Install {clojure-deps-cli} tools version 1.10.3.1069+
.. MacOS
+
[source,bash]
----
brew install clojure/tools/clojure
----
.. Linux
+
Ensure that the following dependencies are installed in OS: `bash`, `curl`, `rlwrap`, and `Java`.
+
[source, bash]
----
curl -O https://download.clojure.org/install/linux-install-1.10.3.1069.sh
chmod +x linux-install-1.10.3.1069.sh
sudo ./linux-install-1.10.3.1069.sh
----

. Install latest {deps-new}
+
[source,bash]
----
clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.4.9"}' :as new
----
+
Tool will be installed in `~/.gitlibs/libs/`

. Install {babashka} v0.4.0+
.. MacOS
+
[source, bash]
----
brew install borkdude/brew/babashka
----
+
.. Linux
+
[source, bash]
----
sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
----

== License

Copyright © 2021 {Author} +
Distributed under the Eclipse Public License 2.0 or (at your option) any later version.
